import type { CategoryNavItem, FilterGroup, ProductCardProps } from "@/features/product/types";

export const PREFERRED_FRAME_TYPES: string[] = [
  "Eyeglasses",
  "Sunglasses",
  "Computer Glasses",
];

export const SEARCH_CATEGORIES: CategoryNavItem[] = [
  { id: "eyeglasses", label: "EYEGLASSES", link: "/search/eyeglasses" },
  { id: "screen-glasses", label: "SCREEN GLASSES", link: "/search/screen-glasses" },
  { id: "kids-glasses", label: "KIDS GLASSES", link: "/search/kids-glasses" },
  { id: "contact-lenses", label: "CONTACT LENSES", link: "/search/contact-lenses" },
  { id: "sunglasses", label: "SUNGLASSES", link: "/search/sunglasses" },
  { id: "collections", label: "COLLECTIONS", link: "/collections" },
  { id: "home-eye-test", label: "HOME EYE-TEST", link: "/online-eye-test" },
  { id: "store-locator", label: "STORE LOCATOR", link: "/stores" },
];

export const SEARCH_FILTERS: FilterGroup[] = [
  {
    id: "frame-type",
    title: "Frame Type",
    type: "shape",
    collapsible: false,
    options: [
      { id: "full-rim", label: "Full Rim", icon: "▢" },
      { id: "rimless", label: "Rimless", icon: "○" },
      { id: "half-rim", label: "Half Rim", icon: "◠" },
    ],
  },
  {
    id: "frame-shape",
    title: "Frame Shape",
    type: "shape",
    collapsible: false,
    options: [
      { id: "square", label: "Square", icon: "▢" },
      { id: "rectangle", label: "Rectangle", icon: "▭" },
      { id: "cat-eye", label: "Cat Eye", icon: "◇" },
      { id: "round", label: "Round", icon: "○" },
      { id: "geometric", label: "Geometric", icon: "⬡" },
      { id: "aviator", label: "Aviator", icon: "◇" },
      { id: "clubmaster", label: "Clubmaster", icon: "▢" },
      { id: "oval", label: "Oval", icon: "⬭" },
    ],
  },
  {
    id: "frame-color",
    title: "Frame Color",
    type: "checkbox",
    collapsible: false,
    options: [
      { id: "black", label: "Black" },
      { id: "transparent", label: "Transparent" },
      { id: "blue", label: "Blue" },
      { id: "gunmetal", label: "Gunmetal" },
      { id: "gold", label: "Gold" },
      { id: "grey", label: "Grey" },
      { id: "silver", label: "Silver" },
      { id: "brown", label: "Brown" },
      { id: "green", label: "Green" },
      { id: "purple", label: "Purple" },
      { id: "pink", label: "Pink" },
      { id: "rose-gold", label: "Rose Gold" },
    ],
  },
  {
    id: "brands",
    title: "Brands",
    type: "checkbox",
    options: [],
  },
];

export const SAMPLE_PRODUCTS: ProductCardProps[] = [
  {
    images: ["/category/image.png", "/banner/image.png"],
    name: "Jachi&Muchi Air",
    description: "Size: Medium • Shades of Steel",
    price: 1600,
    originalPrice: 1990,
    discount: 26,
    rating: 4.8,
    reviews: 11349,
    colors: [
      { colorCode: "#000000", image: "/category/image.png" },
      { colorCode: "#c0c0c0", image: "/banner/image.png" },
      { colorCode: "#8b4513", image: "/category/image.png" },
      { colorCode: "#1e40af", image: "/banner/image.png" },
    ],
    link: "/product/1",
  },
  {
    images: ["/category/image.png", "/banner/image.png"],
    name: "John Jacobs",
    description: "Size: Wide",
    price: 3100,
    originalPrice: 3700,
    discount: 21,
    rating: 4.9,
    reviews: 3675,
    colors: [
      { colorCode: "#000000", image: "/category/image.png" },
      { colorCode: "#8b4513", image: "/banner/image.png" },
    ],
    link: "/product/2",
  },
  {
    images: ["/category/image.png", "/banner/image.png"],
    name: "Vincent Chase",
    description: "Size: Narrow",
    price: 1600,
    originalPrice: 1900,
    discount: 26,
    rating: 4.9,
    reviews: 656,
    colors: [
      { colorCode: "#ffc0cb", image: "/category/image.png" },
      { colorCode: "#ffd700", image: "/banner/image.png" },
    ],
    link: "/product/3",
  },
  {
    images: ["/category/image.png", "/banner/image.png"],
    name: "John Jacobs",
    description: "Size: Medium • John Jacobs",
    price: 3100,
    originalPrice: 3700,
    discount: 21,
    rating: 4.9,
    reviews: 921,
    colors: [
      { colorCode: "#000000", image: "/category/image.png" },
      { colorCode: "#8b4513", image: "/banner/image.png" },
      { colorCode: "#c0c0c0", image: "/category/image.png" },
    ],
    link: "/product/4",
  },
  {
    images: ["/category/image.png", "/banner/image.png"],
    name: "Jachi&Muchi Air",
    description: "Size: Extra Wide",
    price: 2400,
    originalPrice: 2900,
    discount: 17,
    rating: 4.8,
    reviews: 726,
    colors: [
      { colorCode: "#000000", image: "/category/image.png" },
      { colorCode: "#1e40af", image: "/banner/image.png" },
    ],
    link: "/product/5",
  },
  {
    images: ["/category/image.png", "/banner/image.png"],
    name: "John Jacobs",
    description: "Size: Narrow",
    price: 3100,
    originalPrice: 3900,
    discount: 21,
    rating: 4.9,
    reviews: 2999,
    colors: [
      { colorCode: "#f5f5f5", image: "/category/image.png" },
      { colorCode: "#000000", image: "/banner/image.png" },
    ],
    link: "/product/6",
  },
  {
    images: ["/category/image.png", "/banner/image.png"],
    name: "Vincent Chase",
    description: "Size: Medium • Shades of Steel",
    price: 1400,
    originalPrice: 1890,
    discount: 26,
    rating: 4.8,
    reviews: 2059,
    colors: [
      { colorCode: "#000000", image: "/category/image.png" },
      { colorCode: "#8b4513", image: "/banner/image.png" },
      { colorCode: "#c0c0c0", image: "/category/image.png" },
      { colorCode: "#1e40af", image: "/banner/image.png" },
    ],
    link: "/product/7",
  },
  {
    images: ["/category/image.png", "/banner/image.png"],
    name: "John Jacobs",
    description: "Size: Extra Wide",
    price: 4100,
    originalPrice: 4900,
    discount: 16,
    rating: 4.8,
    reviews: 13,
    colors: [
      { colorCode: "#000000", image: "/category/image.png" },
      { colorCode: "#8b4513", image: "/banner/image.png" },
    ],
    link: "/product/8",
  },
  {
    images: ["/category/image.png", "/banner/image.png"],
    name: "Jachi&Muchi Air",
    description: "Size: Premium • AIR FUSION",
    price: 1400,
    originalPrice: 1890,
    discount: 26,
    rating: 4.8,
    reviews: 6890,
    colors: [
      { colorCode: "#f5f5f5", image: "/category/image.png" },
      { colorCode: "#ffc0cb", image: "/banner/image.png" },
      { colorCode: "#87ceeb", image: "/category/image.png" },
    ],
    link: "/product/9",
  },
];
